#!/usr/bin/env bash
# Generate the Caddy site block that serves every env WordPress site over
# HTTPS (TLS phase 2, issue #73): one block listing every host:port combination
# as an address, terminating TLS with certificates from the control-plane
# block's automation policy, and proxying port-for-port to loopback (where
# https-era envs bind their published ports).
#
#   gen-env-sites.sh <bind-ip> <host[,host...]> <port-spec>... > /etc/caddy/env-sites.caddy
#
# <bind-ip>   The droplet's public IP — the interface Caddy listens on.
# <host,...>  Hostname(s) browsers use: a domain, the bare IP, or both
#             (comma-separated) to keep old IP bookmarks working, e.g.
#             "6047box.com,174.138.43.144".
# <port-spec> A range LO-HI or a single PORT; repeat to cover the allocator
#             range PLUS individually migrated legacy envs whose old ports sit
#             outside it, e.g.:  gen-env-sites.sh 1.2.3.4 example.com,1.2.3.4 9100-9299 9047
#
# Then add to /etc/caddy/Caddyfile:   import /etc/caddy/env-sites.caddy
# and reload:                         caddy validate --config /etc/caddy/Caddyfile && systemctl reload caddy
#
# The explicit `bind <bind-ip>` is LOAD-BEARING: without it Caddy listens on
# 0.0.0.0 for each port, which would collide with docker's 127.0.0.1 publishes
# on the same ports (and with the server allocator's loopback port probe).
# Bound to the public IP only, Caddy and docker share each port cleanly.
#
# No `tls` directive here ON PURPOSE: the Caddyfile's GLOBAL options block
# (Caddyfile.example) sets `cert_issuer acme { profile shortlived }`, which
# every site inherits. Per-site tls directives are a trap: Caddy rejects the
# config when a hostname spans site blocks with different host sets
# ("appears in more than one automation policy"). This import therefore
# REQUIRES that global cert_issuer in the importing Caddyfile.
#
# Keep the range in sync with the server's WP_PORT_RANGE (env sites AND their
# app ports allocate from it). Regenerate + reload after widening the range.
set -euo pipefail

if [ $# -lt 3 ]; then
  echo "usage: $0 <bind-ip> <host[,host...]> <port-spec>...   (port-spec: LO-HI or PORT)" >&2
  exit 1
fi
IP="$1"; HOSTS="$2"; shift 2
PORTS=""
for spec in "$@"; do
  case "$spec" in
    *-*) LO="${spec%-*}"; HI="${spec#*-}" ;;
    *)   LO="$spec"; HI="$spec" ;;
  esac
  if ! [ "$LO" -ge 1 ] || ! [ "$HI" -ge "$LO" ] || ! [ "$HI" -le 65535 ]; then
    echo "invalid port spec \"$spec\"" >&2
    exit 1
  fi
  PORTS="$PORTS$(seq "$LO" "$HI")"$'\n'
done
PORTS="$(printf '%s' "$PORTS" | sort -un)"

ADDRS="$(for h in ${HOSTS//,/ }; do printf '%s\n' "$PORTS" | sed "s/^/$h:/"; done | paste -sd, - | sed 's/,/, /g')"

echo "# Generated by gen-env-sites.sh $IP $HOSTS $* — do not edit by hand."
echo "# Katalyst env WordPress sites: TLS for ports $* on $HOSTS, proxied port-for-port to loopback."
# Caddyfile grammar: the opening brace must sit on the same line as the (last)
# site address.
printf '%s {\n' "$ADDRS"
cat <<EOF
	bind $IP
	encode zstd gzip
	reverse_proxy 127.0.0.1:{http.request.local.port}
}
EOF
