#!/usr/bin/env bash
# Generate the Caddy site block that serves every env WordPress site over
# HTTPS (TLS phase 2, issue #73): one block listing every port in the env
# range as an address, terminating TLS with the same short-lived Let's Encrypt
# IP certificate the control plane uses, and proxying port-for-port to
# loopback (where https-era envs bind their published ports).
#
#   gen-env-sites.sh <public-ip> <port-lo> <port-hi> > /etc/caddy/env-sites.caddy
#
# Then add to /etc/caddy/Caddyfile:   import /etc/caddy/env-sites.caddy
# and reload:                         caddy validate --config /etc/caddy/Caddyfile && systemctl reload caddy
#
# The explicit `bind <public-ip>` is LOAD-BEARING: without it Caddy listens on
# 0.0.0.0 for each port, which would collide with docker's 127.0.0.1 publishes
# on the same ports (and with the server allocator's loopback port probe).
# Bound to the public IP only, Caddy and docker share each port cleanly.
#
# Keep the range in sync with the server's WP_PORT_RANGE (env sites AND their
# app ports allocate from it). Regenerate + reload after widening the range.
set -euo pipefail

if [ $# -ne 3 ]; then
  echo "usage: $0 <public-ip> <port-lo> <port-hi>" >&2
  exit 1
fi
IP="$1"; LO="$2"; HI="$3"
if ! [ "$LO" -ge 1 ] || ! [ "$HI" -ge "$LO" ] || ! [ "$HI" -le 65535 ]; then
  echo "invalid port range $LO-$HI" >&2
  exit 1
fi

echo "# Generated by gen-env-sites.sh $IP $LO $HI — do not edit by hand."
echo "# Katalyst env WordPress sites: TLS for ports $LO-$HI, proxied port-for-port to loopback."
# Caddyfile grammar: the opening brace must sit on the same line as the (last)
# site address.
printf '%s {\n' "$(seq "$LO" "$HI" | sed "s/^/$IP:/" | paste -sd, - | sed 's/,/, /g')"
cat <<EOF
	bind $IP
	tls {
		issuer acme {
			profile shortlived
		}
	}
	encode zstd gzip
	reverse_proxy 127.0.0.1:{http.request.local.port}
}
EOF
